{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "fec409bd_b5f9d7cc",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 11
      },
      "lineNbr": 0,
      "author": {
        "id": 1105284
      },
      "writtenOn": "2023-03-22T18:09:51Z",
      "side": 1,
      "message": "Slightly concerned that we don\u0027t have M1 trybot coverage for this. I cannot reproduce any of the tests that fail on Intel locally on M1 but there may be other failures that don\u0027t show up until this lands.",
      "revId": "3b295e9738278e79122bde8867cd8d59cc471785",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}