{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "5653d97c_cf7c1e89",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1105344
      },
      "writtenOn": "2022-03-14T22:17:15Z",
      "side": 1,
      "message": "That\u0027s an assertion failure inside Skia. Not sure whether that might be a flake - cc\u0027ing Brian and Yuly - but let\u0027s try again.\n",
      "revId": "99685a02ed16ff8a7732758ccb9ecf32a74ed65d",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}