{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "f6419f73_d04cdce7",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1300114
      },
      "writtenOn": "2021-11-13T19:21:37Z",
      "side": 1,
      "message": "Might be the reason we were having trouble with libpci failures and fallback to Vulkan in the past?",
      "revId": "d12059aeb31b8e82da38fb47a280a75a1c7f474b",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}