{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "37eefbf8_b2b9c473",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1394635
      },
      "writtenOn": "2023-10-31T00:46:30Z",
      "side": 1,
      "message": "Two isolated tests for the first failing case in the linked issue.",
      "revId": "f6be555207c74275c541567cb6f007fcb54621e8",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}